### ISSUE TITLE
[Ubuntu 16.04] In xenial, gpg --full-generate-key not possible option 

### ISSUE THREAD

**Issue by Dry8r3aD** [ubuntu-kr/ksp-toolkits#4]
Ref: [https://askubuntu.com/questions/1019793/how-to-solve-gpg-invalid-option-full-generate-key](https://askubuntu.com/questions/1019793/how-to-solve-gpg-invalid-option-full-generate-key)

gpg --full-generate-key
-> --gen-key

for ubuntu 16.04

가이드 기준 OS를 명시하고, 버전별로 방법/명령이 조금씩 다르니 이 또한 가이드로 만들면 좋을 것 같네요

**Comment by sukso96100** [comment]
199acefd45019da61cd861a0e2bb23a454ddc772
